// Marken-Liste - alphabetisch sortiert

export const BRAND_OPTIONS: readonly { readonly value: string; readonly label: string }[] = [
  { value: '10DAYS', label: '10DAYS' },
  { value: '8BFT', label: '8BFT' },
  { value: 'A.S.98', label: 'A.S.98' },
  { value: 'AFFENZAHN', label: 'AFFENZAHN' },
  { value: 'ALL SAINTS', label: 'ALL SAINTS' },
  { value: 'AMARANTO', label: 'AMARANTO' },
  { value: 'AMERICAN VINTAGE', label: 'AMERICAN VINTAGE' },
  { value: 'ANA ALCAZAR', label: 'ANA ALCAZAR' },
  { value: 'ANDERSON`S', label: 'ANDERSON`S' },
  { value: 'APPLE OF EDEN', label: 'APPLE OF EDEN' },
  { value: 'ARKK', label: 'ARKK' },
  { value: 'ARMEDANGELS', label: 'ARMEDANGELS' },
  { value: 'ASH', label: 'ASH' },
  { value: 'ASTORFLEX', label: 'ASTORFLEX' },
  { value: 'AUNTS & UNCLES', label: 'AUNTS & UNCLES' },
  { value: 'AUTRY', label: 'AUTRY' },
  { value: 'BACK70', label: 'BACK70' },
  { value: 'BAILEY OF HOLLYWOOD', label: 'BAILEY OF HOLLYWOOD' },
  { value: 'BALL', label: 'BALL' },
  { value: 'BEAUTIFUL SCENTS', label: 'BEAUTIFUL SCENTS' },
  { value: 'BELLROY', label: 'BELLROY' },
  { value: 'BERGAL', label: 'BERGAL' },
  { value: 'BIBI LOU', label: 'BIBI LOU' },
  { value: 'BIRKENSTOCK', label: 'BIRKENSTOCK' },
  { value: 'BLACKROSE', label: 'BLACKROSE' },
  { value: 'BLAUER', label: 'BLAUER' },
  { value: 'BLIZ', label: 'BLIZ' },
  { value: 'BLUNDSTONE', label: 'BLUNDSTONE' },
  { value: 'BNS', label: 'BNS' },
  { value: 'BONDI', label: 'BONDI' },
  { value: 'BORN ORIGINALS', label: 'BORN ORIGINALS' },
  { value: 'BRIXTON', label: 'BRIXTON' },
  { value: 'BUTCHER OF BLUE', label: 'BUTCHER OF BLUE' },
  { value: 'C.P. COMPANY', label: 'C.P. COMPANY' },
  { value: 'CACATOES', label: 'CACATOES' },
  { value: 'CAMPOMAGGI', label: 'CAMPOMAGGI' },
  { value: 'CARHARTT', label: 'CARHARTT' },
  { value: 'CARRANO', label: 'CARRANO' },
  { value: 'CARYATIS', label: 'CARYATIS' },
  { value: 'CAVAL', label: 'CAVAL' },
  { value: 'CLARKS', label: 'CLARKS' },
  { value: 'COACH', label: 'COACH' },
  { value: 'COCCINELLE', label: 'COCCINELLE' },
  { value: 'COLLONIL', label: 'COLLONIL' },
  { value: 'COLORFUL STANDARD', label: 'COLORFUL STANDARD' },
  { value: 'COLUMBIA', label: 'COLUMBIA' },
  { value: 'COOLWAY', label: 'COOLWAY' },
  { value: 'COPENHAGEN', label: 'COPENHAGEN' },
  { value: 'COPENHAGEN MUSE', label: 'COPENHAGEN MUSE' },
  { value: 'CORDWAINER', label: 'CORDWAINER' },
  { value: 'CRAFTON', label: 'CRAFTON' },
  { value: 'CULTI', label: 'CULTI' },
  { value: 'D_B', label: 'D_B' },
  { value: 'DEBLON SPORTS', label: 'DEBLON SPORTS' },
  { value: 'DELUXE', label: 'DELUXE' },
  { value: 'DENHAM', label: 'DENHAM' },
  { value: 'DEUS EX MACHINA', label: 'DEUS EX MACHINA' },
  { value: 'DFP', label: 'DFP' },
  { value: 'DOLOMITE', label: 'DOLOMITE' },
  { value: 'DONKEY', label: 'DONKEY' },
  { value: 'DR.MARTENS', label: 'DR.MARTENS' },
  { value: 'DRYKORN', label: 'DRYKORN' },
  { value: 'DSTREZZED', label: 'DSTREZZED' },
  { value: 'DUCATI', label: 'DUCATI' },
  { value: 'DUUO', label: 'DUUO' },
  { value: 'EDBLAD', label: 'EDBLAD' },
  { value: 'ELITE', label: 'ELITE' },
  { value: 'ELVINE', label: 'ELVINE' },
  { value: 'ERENDIRA', label: 'ERENDIRA' },
  { value: 'ESCAPULARI', label: 'ESCAPULARI' },
  { value: 'FAST AND BRIGHT', label: 'FAST AND BRIGHT' },
  { value: 'FELMINI', label: 'FELMINI' },
  { value: 'FILSON', label: 'FILSON' },
  { value: 'FLAMINGOS LIFE', label: 'FLAMINGOS LIFE' },
  { value: 'FLORIS VAN BOMMEL', label: 'FLORIS VAN BOMMEL' },
  { value: 'FLOWER MOUNTAIN', label: 'FLOWER MOUNTAIN' },
  { value: 'FRAU TONIS PARFUM', label: 'FRAU TONIS PARFUM' },
  { value: 'FRED PERRY', label: 'FRED PERRY' },
  { value: 'FREDSBRUDER', label: 'FREDSBRUDER' },
  { value: 'FRONT STREET 8', label: 'FRONT STREET 8' },
  { value: 'GASTON LUGA', label: 'GASTON LUGA' },
  { value: 'GENESIS', label: 'GENESIS' },
  { value: 'GIANNI CHIARINI', label: 'GIANNI CHIARINI' },
  { value: 'GIOVE', label: 'GIOVE' },
  { value: 'GOOD NEWS', label: 'GOOD NEWS' },
  { value: 'GOT BAG', label: 'GOT BAG' },
  { value: 'HAPPYSOCKS', label: 'HAPPYSOCKS' },
  { value: 'HERZENS ANGELEGENHEIT', label: 'HERZENS ANGELEGENHEIT' },
  { value: 'HIDNANDER', label: 'HIDNANDER' },
  { value: 'HIDESINS', label: 'HIDESINS' },
  { value: 'HKLIVING', label: 'HKLIVING' },
  { value: 'HOFF', label: 'HOFF' },
  { value: 'HOMECORE', label: 'HOMECORE' },
  { value: 'HOUSE OF YARN', label: 'HOUSE OF YARN' },
  { value: 'HUB FOOTWEAR', label: 'HUB FOOTWEAR' },
  { value: 'HULKEN', label: 'HULKEN' },
  { value: 'HUMBLE LIGHTS', label: 'HUMBLE LIGHTS' },
  { value: 'I´M BRIAN', label: 'I´M BRIAN' },
  { value: 'ILSE JACOBSEN', label: 'ILSE JACOBSEN' },
  { value: 'INUIKII', label: 'INUIKII' },
  { value: 'JANICE', label: 'JANICE' },
  { value: 'JASON MARKK', label: 'JASON MARKK' },
  { value: 'JUICY COUTURE', label: 'JUICY COUTURE' },
  { value: 'KANGOL', label: 'KANGOL' },
  { value: 'KEEN', label: 'KEEN' },
  { value: 'KOMONO', label: 'KOMONO' },
  { value: 'LAERKE-SHOES', label: 'LAERKE-SHOES' },
  { value: 'LAKRIDS BY BÜLOW', label: 'LAKRIDS BY BÜLOW' },
  { value: 'LALA BERLIN', label: 'LALA BERLIN' },
  { value: 'LASSE', label: 'LASSE' },
  { value: 'LAZAMANI', label: 'LAZAMANI' },
  { value: 'LE BONNET', label: 'LE BONNET' },
  { value: 'LE TEMPS', label: 'LE TEMPS' },
  { value: 'LEMON JELLY', label: 'LEMON JELLY' },
  { value: 'LES HOMMES', label: 'LES HOMMES' },
  { value: 'LIEBESKIND BERLIN', label: 'LIEBESKIND BERLIN' },
  { value: 'LIV BERGEN', label: 'LIV BERGEN' },
  { value: 'LUA', label: 'LUA' },
  { value: 'MATHMOS', label: 'MATHMOS' },
  { value: 'MAYBE', label: 'MAYBE' },
  { value: 'ME369', label: 'ME369' },
  { value: 'MELINE', label: 'MELINE' },
  { value: 'MERCER', label: 'MERCER' },
  { value: 'MICA BARCELONA', label: 'MICA BARCELONA' },
  { value: 'MICHAEL KORS', label: 'MICHAEL KORS' },
  { value: 'MIMMU', label: 'MIMMU' },
  { value: 'MISS GOODLIFE', label: 'MISS GOODLIFE' },
  { value: 'MIZUNO', label: 'MIZUNO' },
  { value: 'MJUS', label: 'MJUS' },
  { value: 'MOA CONCEPT', label: 'MOA CONCEPT' },
  { value: 'MOLLIOLLI', label: 'MOLLIOLLI' },
  { value: 'MOMA', label: 'MOMA' },
  { value: 'MY JEWELLERY', label: 'MY JEWELLERY' },
  { value: 'NADIA DAFRI', label: 'NADIA DAFRI' },
  { value: 'NANKU', label: 'NANKU' },
  { value: 'NATURAL WORLD', label: 'NATURAL WORLD' },
  { value: 'NEBO', label: 'NEBO' },
  { value: 'NERO GIARDINI', label: 'NERO GIARDINI' },
  { value: 'NICE PIECE', label: 'NICE PIECE' },
  { value: 'NIO', label: 'NIO' },
  { value: 'NN. 07', label: 'NN. 07' },
  { value: 'NOBRAND', label: 'NOBRAND' },
  { value: 'NUBIKK', label: 'NUBIKK' },
  { value: 'NUDIE JEANS', label: 'NUDIE JEANS' },
  { value: 'OAS', label: 'OAS' },
  { value: 'OAKLEY', label: 'OAKLEY' },
  { value: 'OH APRIL', label: 'OH APRIL' },
  { value: 'ON', label: 'ON' },
  { value: 'ON RUNNING', label: 'ON RUNNING' },
  { value: 'OTTOD`AME', label: 'OTTOD`AME' },
  { value: 'PEDRO MIRALLES', label: 'PEDRO MIRALLES' },
  { value: 'PENN&INK', label: 'PENN&INK' },
  { value: 'PINQPONQ', label: 'PINQPONQ' },
  { value: 'PLAKTON', label: 'PLAKTON' },
  { value: 'POM AMSTERDAM', label: 'POM AMSTERDAM' },
  { value: 'PORTUGUESE FLANNEL', label: 'PORTUGUESE FLANNEL' },
  { value: 'PREMIATA', label: 'PREMIATA' },
  { value: 'PRESENT TIME', label: 'PRESENT TIME' },
  { value: 'PURAAI', label: 'PURAAI' },
  { value: 'PURPLE', label: 'PURPLE' },
  { value: 'QLAVINE', label: 'QLAVINE' },
  { value: 'RAAW ALCHEMY', label: 'RAAW ALCHEMY' },
  { value: 'RAS', label: 'RAS' },
  { value: 'RAY BAN', label: 'RAY BAN' },
  { value: 'RICH & ROYAL', label: 'RICH & ROYAL' },
  { value: 'ROARK', label: 'ROARK' },
  { value: 'ROSA STERN', label: 'ROSA STERN' },
  { value: 'RUN OF', label: 'RUN OF' },
  { value: 'SAINT BARTH', label: 'SAINT BARTH' },
  { value: 'SANDQVIST', label: 'SANDQVIST' },
  { value: 'SCANDINAVIAN EDITION', label: 'SCANDINAVIAN EDITION' },
  { value: 'SCHOLL', label: 'SCHOLL' },
  { value: 'SCHOTT NYC', label: 'SCHOTT NYC' },
  { value: 'SEAMLESS', label: 'SEAMLESS' },
  { value: 'SERGIO TACCHINI', label: 'SERGIO TACCHINI' },
  { value: 'SHOES.PLEASE.', label: 'SHOES.PLEASE.' },
  { value: 'SHOOT', label: 'SHOOT' },
  { value: 'SHOUIA', label: 'SHOUIA' },
  { value: 'SINCERE', label: 'SINCERE' },
  { value: 'SMITTEN', label: 'SMITTEN' },
  { value: 'SOAKED', label: 'SOAKED' },
  { value: 'SOLITAIRE', label: 'SOLITAIRE' },
  { value: 'SOLO TWENTYFIVE', label: 'SOLO TWENTYFIVE' },
  { value: 'SORBET ISLAND', label: 'SORBET ISLAND' },
  { value: 'SOREL', label: 'SOREL' },
  { value: 'SORENA', label: 'SORENA' },
  { value: 'STANCE', label: 'STANCE' },
  { value: 'STELLAMARI', label: 'STELLAMARI' },
  { value: 'STETSON', label: 'STETSON' },
  { value: 'STRYPE', label: 'STRYPE' },
  { value: 'SUN OF A BEACH', label: 'SUN OF A BEACH' },
  { value: 'SUN68', label: 'SUN68' },
  { value: 'SUPERGA', label: 'SUPERGA' },
  { value: 'TADASHI', label: 'TADASHI' },
  { value: 'THEA MIKA', label: 'THEA MIKA' },
  { value: 'THE NORTH FACE', label: 'THE NORTH FACE' },
  { value: 'THREE BY ONE', label: 'THREE BY ONE' },
  { value: 'TIMBERLAND', label: 'TIMBERLAND' },
  { value: 'TOMS', label: 'TOMS' },
  { value: 'TOPOLOGIE', label: 'TOPOLOGIE' },
  { value: 'TRANSPARENT', label: 'TRANSPARENT' },
  { value: 'UGG', label: 'UGG' },
  { value: 'UNIVERSAL', label: 'UNIVERSAL' },
  { value: 'VAGABOND', label: 'VAGABOND' },
  { value: 'VALENTINA', label: 'VALENTINA' },
  { value: 'VEJA', label: 'VEJA' },
  { value: 'VERBENAS', label: 'VERBENAS' },
  { value: 'VOILE BLANCHE', label: 'VOILE BLANCHE' },
  { value: 'VONDELS', label: 'VONDELS' },
  { value: 'WILD DONKEY', label: 'WILD DONKEY' },
  { value: 'WOOLPOWER', label: 'WOOLPOWER' },
  { value: 'YOHJIYAMA', label: 'YOHJIYAMA' },
  { value: 'YOKONO', label: 'YOKONO' },
  { value: 'ZHRILL', label: 'ZHRILL' },
];
