// Zalando Silhouetten-Attribute — generiert aus zalando_attribute_manu.xlsx
// NUR mandatory Attribute (Pflichtfelder)

export type AttributeRequirement = 'mandatory';

export interface ZalandoAttribute {
  readonly key: string;
  readonly label: string;
  readonly requirement: AttributeRequirement;
  readonly type: 'text' | 'select' | 'number' | 'textarea';
  readonly options?: readonly string[];
  readonly notApplicable?: boolean;
}

export interface ZalandoSilhouette {
  readonly key: string;
  readonly label: string;
  readonly attributes: readonly ZalandoAttribute[];
  readonly imageType: 'shoes' | 'clothing' | 'accessories';
}

// ─── Hilfsfunktionen ────────────────────────────────────────────────────────────

export function getSilhouetteByKey(key: string): ZalandoSilhouette | undefined {
  return ZALANDO_SILHOUETTES.find(s => s.key === key);
}

export function getSilhouetteOptions(): readonly { value: string; label: string }[] {
  return ZALANDO_SILHOUETTES.map(s => ({ value: s.key, label: s.label }));
}

// ─── Silhouetten ─────────────────────────────────────────────────────────────

export const ZALANDO_SILHOUETTES: readonly ZalandoSilhouette[] = [
  {
    key: 'ankle_boots',
    label: 'Stiefeletten',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'backless_slipper',
    label: 'Pantoletten',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'backpack',
    label: 'Rucksack',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'bag',
    label: 'Tasche',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'ballerina_shoe',
    label: 'Ballerinas',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'belt',
    label: 'Gürtel',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'boots',
    label: 'Stiefel',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'cardigan',
    label: 'Strickjacke',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'coat',
    label: 'Mantel',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_faux_fur_collar_material', label: 'Faux fur collar Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_lining', label: 'Inner jacket lining', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_outer_material', label: 'Inner jacket outer Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_padding', label: 'Inner jacket padding', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_middle_layer_material', label: 'Middle layer Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_outer_jacket_inner_material', label: 'Outer jacket inner Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_sleeve_lining', label: 'Sleeve lining', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_trim_material', label: 'Trim Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'combination_clothing',
    label: 'Kombinationsbekleidung / Sets',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'dress',
    label: 'Kleid',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'etui',
    label: 'Etui',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'gloves',
    label: 'Handschuhe',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_outer_jacket_inner_material', label: 'Outer jacket inner Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'headgear',
    label: 'Kopfbedeckung',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_outer_jacket_inner_material', label: 'Outer jacket inner Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'jacket',
    label: 'Jacke',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_faux_fur_collar_material', label: 'Faux fur collar Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_lining', label: 'Inner jacket lining', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_outer_material', label: 'Inner jacket outer Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_inner_jacket_padding', label: 'Inner jacket padding', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_middle_layer_material', label: 'Middle layer Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_outer_jacket_inner_material', label: 'Outer jacket inner Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_sleeve_lining', label: 'Sleeve lining', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_trim_material', label: 'Trim Material', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'low_shoe',
    label: 'Halbschuhe',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'one_piece_suit',
    label: 'Jumpsuit / Overall',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'pullover',
    label: 'Pullover',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'pumps',
    label: 'Pumps',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'sandals',
    label: 'Sandalen',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'shirt',
    label: 'Hemd',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'shoe_accessoires',
    label: 'Schuhzubehör',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
      { key: 'volume_ml', label: 'Volume ml', requirement: 'mandatory', type: 'number' },
    ],
  },
  {
    key: 'skirt',
    label: 'Rock',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'sneaker',
    label: 'Sneaker',
    imageType: 'shoes',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 't_shirt_top',
    label: 'T-Shirt / Top',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_sleeves', label: 'Obermaterial sleeves', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'travel_equipment',
    label: 'Reisegepäck / Reiseaccessoires',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'trouser',
    label: 'Hose',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'vest',
    label: 'Weste',
    imageType: 'clothing',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'material_filling', label: 'Filling', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_futter_clothing', label: 'Futter Produkt', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_back', label: 'Obermaterial Rückseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_bottom', label: 'Obermaterial bottom', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_clothing', label: 'Hauptmaterial', requirement: 'mandatory', type: 'text' },
      { key: 'material_upper_material_front', label: 'Obermaterial Vorderseite', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_insert', label: 'Obermaterial insert', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_middle', label: 'Obermaterial middle', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'material_upper_material_top', label: 'Obermaterial top', requirement: 'mandatory', type: 'text', notApplicable: true },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
  {
    key: 'wallet',
    label: 'Geldbörse / Portemonnaie',
    imageType: 'accessories',
    attributes: [
      { key: 'brand_code', label: 'Marke', requirement: 'mandatory', type: 'text' },
      { key: 'color_code_primary', label: 'Hauptfarbe', requirement: 'mandatory', type: 'select', options: ['beige', 'black', 'blue', 'brown', 'gold', 'green', 'grey', 'multicoloured', 'olive', 'orange', 'petrol', 'pink', 'purple', 'red', 'silver', 'turquoise', 'white', 'yellow'] },
      { key: 'description', label: 'Produktbeschreibung', requirement: 'mandatory', type: 'textarea' },
      { key: 'ean', label: 'EAN / GTIN', requirement: 'mandatory', type: 'text' },
      { key: 'media', label: 'Medien', requirement: 'mandatory', type: 'text' },
      { key: 'name', label: 'Produktname', requirement: 'mandatory', type: 'text' },
      { key: 'season_code', label: 'Saison', requirement: 'mandatory', type: 'select', options: ['FS25', 'HW25', 'FS26', 'HW26', 'NOOS'] },
      { key: 'size_codes', label: 'Größenangaben', requirement: 'mandatory', type: 'text' },
      { key: 'size_group', label: 'Größensystem', requirement: 'mandatory', type: 'select', options: ['EU', 'DE', 'UK', 'US', 'IT', 'FR'] },
      { key: 'target_age_groups', label: 'Altersgruppe', requirement: 'mandatory', type: 'select', options: ['Erwachsene', 'Kinder', 'Baby', 'Teenager'] },
      { key: 'target_genders', label: 'Geschlecht', requirement: 'mandatory', type: 'select', options: ['Herren', 'Damen', 'Unisex', 'Kinder'] },
    ],
  },
];

